[package]
name = "sdm845-abootctl"
version = "0.4.0"
authors = ["aissa <aissa.zenaida@pm.me>", "caleb <caleb@connolly.tech>"]
edition = "2018"

[dependencies]
gpt = "2.0.0"
clap = "2.33.3"
block-utils = "0.10.2"
modular-bitfield = "0.11.2"
