[package]
name = "sdm845-abootctl"
version = "0.1.1"
authors = ["aissa <aissa.zenaida@pm.me>", "caleb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpt = "2.0.0"
clap = "2.33.3"
